vim.keymap.set("n", "-", "<cmd>Oil --float<CR>", { desc = "Open parent directory" })

-- keymaps for nvim-treesitter-textobjects
vim.keymap.set("n", "<leader>a", function()
	require("nvim-treesitter-textobjects.swap").swap_next("@parameter.inner")
end)
vim.keymap.set("n", "<leader>A", function()
	require("nvim-treesitter-textobjects.swap").swap_previous("@parameter.outer")
end)

-- keymaps for fzf
vim.keymap.set("n", "<leader>ff", function()
	require("fzf-lua").files()
end, { desc = "[F]ind [F]ile in current project directory" })
vim.keymap.set("n", "<leader>fg", function()
	require("fzf-lua").live_grep()
end, { desc = "Live grepping in current project directory" })
vim.keymap.set("n", "<leader>fc", function()
	require("fzf-lua").files({ cwd = vim.fn.stdpath("config") })
end, { desc = "[F]ind [C]onfiguration in Neovim directory" })
vim.keymap.set("n", "<leader>fb", function()
	require("fzf-lua").builtin()
end, { desc = "[F]ind [B]uiltin fuzzies for the fzf" })
vim.keymap.set("n", "<leader>fh", function()
	require("fzf-lua").helptags()
end, { desc = "[F]ind [H]elp" })
vim.keymap.set("n", "<leader>fk", function()
	require("fzf-lua").keymaps()
end, { desc = "[F]ind [K]eymaps" })
vim.keymap.set("n", "<leader><leader>", function()
	require("fzf-lua").buffers()
end, { desc = "Open buffers" })
vim.keymap.set("n", "<leader>fo", function()
	require("fzf-lua").oldfiles()
end, { desc = "[F]ind [O]ld files" })
vim.keymap.set("n", "<leader>/", function()
	require("fzf-lua").lgrep_curbuf()
end, { desc = "live grep current file or buffer" })
vim.keymap.set("n", "<leader>fr", function()
	require("fzf-lua").resume()
end, { desc = "[F]ind [R]esume" })

-- keymap for diagnostic floated window
vim.keymap.set("n", "gl", function()
	vim.diagnostic.open_float()
end, { desc = "Open the next diagnostic in floated window" })
